export type RequestValidationErrorType =
  | 'INVALID_REQUEST_BODY'
  | 'INVALID_REQUEST_PARAMS'
  | 'INVALID_REQUEST_QUERY_PARAMS'

export enum RequestValidationErrorTypeEnum {
  INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
  INVALID_REQUEST_PARAMS = 'INVALID_REQUEST_PARAMS',
  INVALID_REQUEST_QUERY_PARAMS = 'INVALID_REQUEST_QUERY_PARAMS',
}
